# Generated by Django 3.2.25 on 2025-04-19 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='imporant',
            new_name='important',
        ),
    ]
